apiVersion: apps/v1
kind: Deployment
metadata:
  name: gridlock-deployment
  namespace: default
  labels:
    app: gridlock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gridlock
  template:
    metadata:
      labels:
        app: gridlock
    spec:
      containers:
      - name: gridlock-container
        image: mcardy.azurecr.io/gridlock:$BUILD_NUMBER
        ports:
        - containerPort: 80
          name: http
      imagePullSecrets:
      - name: regcred